#!/bin/bash

# Load nvm so npm command is found
export NVM_DIR="/usr/local/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

unset GIT_DIR

# We'll use this for the release folder name
DATE=$(date +"%Y%m%d%H%M")

# Where our repo lives
REPO_PATH=/var/www/mrm.group/repo.git

# Cater for multiple similtaneous branch pushes
while read oldrev newrev refname
do
    # Get name of branch that is being pushed
    BRANCH=$(git rev-parse --symbolic --abbrev-ref $refname)

    # Web root
    WWW_ROOT=/var/www/mrm.group

    if [ "$BRANCH" != "master" ]; then
        # We're not on master, so switch to staging
        WWW_ROOT=$WWW_ROOT/subdomains/staging
    fi

    # Set deployment paths
    WWW_CURRENT=$WWW_ROOT/current
    WWW_RELEASES=$WWW_ROOT/releases
    WWW_RELEASE=$WWW_RELEASES/$DATE

    # Debugging info
    echo "---"
    echo "Branch: $BRANCH"
    echo "Release: $DATE"
    echo "---"

    # Create new release folder if it does not exist
    if [ ! -d $WWW_RELEASE ]; then mkdir $WWW_RELEASE; fi

    # Set working tree to this release and checkout repo
    git --work-tree=$WWW_RELEASE --git-dir=$REPO_PATH checkout $BRANCH -f

    # Install gems
    cd $WWW_RELEASE

    bundle install --path vendor/bundle

    # Get data from Contentful
    CONTENTFUL_ACCESS_TOKEN=XXX CONTENTFUL_SPACE_ID=XXX bundle exec jekyll contentful

    # Install node modules
    npm install

	  # Build front end
    bundle exec jekyll build --config source/jekyll/_config.yml
    gulp --prod

    # Remove all but last 5 releases
    ls -trd $WWW_RELEASES/* | head -n -5 | xargs rm -rf

    # Symlink new release as current
    ln -sfn $WWW_RELEASE/public $WWW_CURRENT

done
